package com.jibaru.random.view;

import com.jibaru.random.model.Random;
import com.jibaru.random.model.RandomCongruentialMultiplicative;
import com.jibaru.random.model.RandomJava;
import com.jibaru.random.model.RandomLinearCongruential;
import com.jibaru.random.model.RandomMidSquare;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class MainJFrame extends javax.swing.JFrame {

    private Random random;
    private final DefaultListModel listModel = new DefaultListModel();
    private final JFileChooser jFileChooser = new JFileChooser();

    public MainJFrame() {
        initComponents();
        lstNumbers.setModel(listModel);
        jFileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        ActionListener actionListener = (ActionEvent e) -> {
            if (rdMidSquare.isSelected() || rdJavaRandom.isSelected()) {
                txtA.setEnabled(false);
                txtC.setEnabled(false);
                txtM.setEnabled(false);
            } else if (rdLinearCongruential.isSelected()) {
                txtA.setEnabled(true);
                txtC.setEnabled(true);
                txtM.setEnabled(true);
            } else if (rdCongruencialMulti.isSelected()) {
                txtA.setEnabled(true);
                txtC.setEnabled(false);
                txtM.setEnabled(true);
            }
        };

        rdMidSquare.addActionListener(actionListener);
        rdLinearCongruential.addActionListener(actionListener);
        rdCongruencialMulti.addActionListener(actionListener);
        rdJavaRandom.addActionListener(actionListener);
    }

    void buildNumbers() {
        long seed;
        long size;

        try {
            seed = Long.parseLong(txtSeed.getText());
            size = Long.parseLong(txtSize.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese seed y cantidad");
            return;
        }

        if (rdMidSquare.isSelected()) {
            random = new RandomMidSquare(seed, size);
        } else if (rdLinearCongruential.isSelected()) {
            long a;
            long c;
            long m;

            try {
                a = Long.parseLong(txtA.getText());
                c = Long.parseLong(txtC.getText());
                m = Long.parseLong(txtM.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Ingrese a, c y m");
                return;
            }

            random = new RandomLinearCongruential(seed, a, c, m, size);
        } else if (rdCongruencialMulti.isSelected()) {
            long a;
            long m;

            try {
                a = Long.parseLong(txtA.getText());
                m = Long.parseLong(txtM.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Ingrese a y m");
                return;
            }

            random = new RandomCongruentialMultiplicative(seed, a, m, size);
        } else if (rdJavaRandom.isSelected()) {
            random = new RandomJava(seed, size);
        } else {
            random = null;
        }

        if (random != null) {
            listModel.clear();

            while (random.hasNext()) {
                listModel.addElement(random.getNext());
            }

            btnExport.setEnabled(true);
        }
    }

    void exportToTxt() {
        jFileChooser.showSaveDialog(this);

        File file = jFileChooser.getSelectedFile();

        if (file != null) {
            FileWriter fileWriter;

            try {
                fileWriter = new FileWriter(file, true);

                String text = "";

                for (int i = 0; i < listModel.size(); i++) {
                    text += Double.toString((double) listModel.get(i)) + "\r\n";
                }

                fileWriter.write(text);
                fileWriter.close();

            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al guardar, no existe nombre");
            }
        }
    }

    void showCredits() {
        JOptionPane.showMessageDialog(this, "Creado por Jibaru");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        rdType = new javax.swing.ButtonGroup();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnGenerate = new javax.swing.JButton();
        rdMidSquare = new javax.swing.JRadioButton();
        rdLinearCongruential = new javax.swing.JRadioButton();
        rdCongruencialMulti = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstNumbers = new javax.swing.JList<>();
        btnExport = new javax.swing.JButton();
        txtSeed = new javax.swing.JFormattedTextField();
        txtSize = new javax.swing.JFormattedTextField();
        txtA = new javax.swing.JFormattedTextField();
        txtC = new javax.swing.JFormattedTextField();
        txtM = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rdJavaRandom = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        jItemCredits = new javax.swing.JMenuItem();
        jItemExit = new javax.swing.JMenuItem();

        jFormattedTextField1.setText("jFormattedTextField1");

        jFormattedTextField2.setText("jFormattedTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Random Number Generator");
        setResizable(false);

        jLabel1.setText("Seed");

        jLabel2.setText("Cantidad");

        jLabel3.setText("a:");

        jLabel4.setText("c:");

        jLabel5.setText("m:");

        btnGenerate.setText("Generar");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });

        rdType.add(rdMidSquare);
        rdMidSquare.setSelected(true);
        rdMidSquare.setText("Cuadrado Medio");

        rdType.add(rdLinearCongruential);
        rdLinearCongruential.setText("Lineal Congruencial");

        rdType.add(rdCongruencialMulti);
        rdCongruencialMulti.setText("Congruencial Multiplicativo");

        jScrollPane1.setViewportView(lstNumbers);

        btnExport.setText("Exportar TXT");
        btnExport.setEnabled(false);
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        txtSeed.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        txtSize.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        txtA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtA.setEnabled(false);

        txtC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtC.setEnabled(false);

        txtM.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtM.setEnabled(false);

        jLabel6.setText("Método");

        jLabel7.setText("By Jibaru");

        rdType.add(rdJavaRandom);
        rdJavaRandom.setText("Java Random");

        jMenu.setText("Menú");
        jMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuActionPerformed(evt);
            }
        });

        jItemCredits.setText("Cŕeditos");
        jItemCredits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemCreditsActionPerformed(evt);
            }
        });
        jMenu.add(jItemCredits);

        jItemExit.setText("Salir");
        jItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemExitActionPerformed(evt);
            }
        });
        jMenu.add(jItemExit);

        jMenuBar1.add(jMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtSeed, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(rdMidSquare, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rdLinearCongruential, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rdCongruencialMulti, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdJavaRandom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(txtA, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtC, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(btnGenerate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtM, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(btnExport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(1, 1, 1)
                        .addComponent(rdMidSquare)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdLinearCongruential)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdCongruencialMulti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdJavaRandom)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGenerate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        buildNumbers();
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        exportToTxt();
    }//GEN-LAST:event_btnExportActionPerformed

    private void jMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuActionPerformed

    private void jItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemExitActionPerformed
        dispose();
    }//GEN-LAST:event_jItemExitActionPerformed

    private void jItemCreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemCreditsActionPerformed
        showCredits();
    }//GEN-LAST:event_jItemCreditsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JMenuItem jItemCredits;
    private javax.swing.JMenuItem jItemExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstNumbers;
    private javax.swing.JRadioButton rdCongruencialMulti;
    private javax.swing.JRadioButton rdJavaRandom;
    private javax.swing.JRadioButton rdLinearCongruential;
    private javax.swing.JRadioButton rdMidSquare;
    private javax.swing.ButtonGroup rdType;
    private javax.swing.JFormattedTextField txtA;
    private javax.swing.JFormattedTextField txtC;
    private javax.swing.JFormattedTextField txtM;
    private javax.swing.JFormattedTextField txtSeed;
    private javax.swing.JFormattedTextField txtSize;
    // End of variables declaration//GEN-END:variables
}
